### DISCUSSION TITLE
A minimal Docker Compose configuration for deploying Paisa

### DISCUSSION THREAD

**Discussion by avinal** [ananthakumaran/paisa#165] [Show and tell]
I am using Raspberry Pi 5 as my home server. This is a minimal configuration for deploying the app.
```yaml
version: '3.7'

services:
  paisa:
    image: ananthakumaran/paisa:v0.6.4
    volumes:
      - /your-host-folder-here/:/root/Documents/paisa/
    ports:
      - "7500:7500"
    restart: unless-stopped
```
Please update the `your-host-folder-here` or use an .env file.
