### ISSUE TITLE
Stocks and MF price not updated when using Yahoo Finance as source

### ISSUE THREAD

**Issue by jdeva** [ananthakumaran/paisa#168]
Below is my commodity setup in my test config file.

```
commodities:
    - name: Quant Mid Cap Dir Gr
      type: mutualfund
      price:
        provider: com-yahoo
        code: 0P0000XW4V.BO
      harvest: 1095
      tax_category: equity65
    - name: IRFC
      type: stock
      price:
        provider: com-yahoo
        code: IRFC.NS
      harvest: 0
      tax_category: equity
    - name: RVNL
      type: stock
      price:
        provider: com-yahoo
        code: RVNL.NS
      harvest: 0
      tax_category: equity
```

And a sample entry would be 

```
2024-01-18 Investment
; Stock purchase : IRFC
Assets:Equity:Stocks                          50 IRFC @  142.00 INR
Assets:Checking:Wallet:Zerodha 
```

However this doesn't update the price under `Ledger > Price`

I have my app running on pikapods.
