### ISSUE TITLE
Error on goal view

### ISSUE THREAD

**Issue by tribly** [ananthakumaran/paisa#180]
**Describe your Environment**
OS: Arch Linux
Paisa Version: 0.6.5-1
App Variant: Desktop

**Describe the bug**
Opening a goal ends in error

**To Reproduce**
1. Go to 'goals page'
2. Click on a goal

```
Og@http://localhost:7500/_app/immutable/chunks/ProgressWithBreakpoints.UtLwf9L_.js:1:296775
oQ@http://localhost:7500/_app/immutable/chunks/ProgressWithBreakpoints.UtLwf9L_.js:1:296701
ft/<@http://localhost:7500/_app/immutable/nodes/35.fqP1kAQO.js:1:8311

Please report this issue at https://github.com/ananthakumaran/paisa/issues. Closing and reopening the app may help.
```
**Expected behavior**
Viewing a goal description.

**Comment by ananthakumaran** [comment]
Do you have any goals? If so can you share the config here and the current balance

**Comment by tribly** [comment]
```
goals:
    retirement: []
    savings:
        - name: Thing
          icon: mdi:youtube-gaming
          target: 210
          target_date: ""
          rate: 0
          payment_per_period: 0
          accounts:
            - Assets:Wishlist:Thing
          priority: 3
```

Basically this. With no balance in `Assets:Wishlist:*`
