### ISSUE TITLE
Prices for stocks are not being updated from yahoo

### ISSUE THREAD

**Issue by praveendhawan** [ananthakumaran/paisa#218]
**Describe your Environment**
OS: Mac Sonoma (silicon)
Paisa Version: 0.6.6
App Variant: Desktop

**Describe the bug**
I have added commodities for stocks with price tickers from yahoo. But when I update prices, the error is raised. Also clicking cross button on error doesn't close the error popup.

**To Reproduce**
1. Open Paisa Application
2. Click on 3 dots on right top
3. Choose "Update Prices"
4. Error happens

**Expected behavior**
I would have expected it to update prices with current prices and show me gains etc.

**Screenshots**
<img width="1051" alt="image" src="https://github.com/ananthakumaran/paisa/assets/12948906/66b7ea5f-8b44-4a27-b496-3e567fb5bbb0">
<img width="1447" alt="image" src="https://github.com/ananthakumaran/paisa/assets/12948906/19c83274-faf9-4a59-84bb-598dd94db458">

**Journal Entries**
`paisa.yml` commodities entries
```
commodities:
    - name: MAZDOCK
      type: stock
      price:
        provider: com-yahoo
        code: MAZDOCK.BO
      harvest: 0
      tax_category: equity
```
accounts entries
```
account Assets:Equity:Stocks:MAZDOCK                   
  ; type: Asset
```
transactions entries
```
2023/12/15 Opening Balances
    Assets:Equity:Stocks:MAZDOCK                   1   MAZDOCK	  @  ₹ 2,037.00
    Equity:OpeningBalance               -₹ 2,037
```
