### ISSUE TITLE
Stock prices not getting updated from Yahoo finance

### ISSUE THREAD

**Issue by gvijayakumar-16** [ananthakumaran/paisa#323]
Hi,

I have been running paisa via docker image.

Recently the stock prices via yahoo are not getting updated and getting the below error.

![Image](https://github.com/user-attachments/assets/b9212140-ae9c-48fe-b0bc-d1f482a35203)

When tried via alpha vantage, it updates properly.

Config when using yahoo 

```
- name: COALINDIA
      type: stock
      price:
        provider: com-yahoo
        code: COALINDIA.NS
      harvest: 0
      tax_category: equity
```

These errors started happening very recently and it was updating properly a few days back. Anything I might have missed?
