### ISSUE TITLE
Price taken as 0 for Yahoo/Mutual Funds API - for today's date

### ISSUE THREAD

**Issue by vivekmittal** [ananthakumaran/paisa#338]
**Describe your Environment**
OS: Mac Sequoia (silicon)
Paisa Version: 0.7.2
App Variant: Desktop

**Describe the bug**
The price fetched for the Mutual funds is coming as 0 for almost all mutual funds. This breaks the returns calculation as well as doesn't really reflect the updated prices anywhere on the app.

**To Reproduce**
- Try to define a commodity = Mutual Fund using Yahoo (can take HDFC DIVIDEND YIELD FUND - DIRECT GROWTH PLAN) [Yahoo Ticker: 0P0001L6NT.BO]
```
Commodity Definition

    - name: HDFC_DIVIDEND_YIELD_GROWTH_DIRECT_PLAN
      type: mutualfund
      price:
        provider: com-yahoo
        code: 0P0001L6NT.BO
      harvest: 0
      tax_category: equity
```
- Update prices
- The price is updated correctly for day before today - but today's price is always 0

**Expected behavior**
For mutual funds, it should probably take the price of T-1 day and not today

**Screenshots**
<img width="1508" alt="Image" src="https://github.com/user-attachments/assets/efef5223-cd9b-4061-ac23-b912111f5afa" />

**Journal**
```
2025/03/31 Mutual Funds Vivek
    Assets:Equity:MF:HDFC Dividend Yield Growth Direct Plan    23057.0330 HDFC_DIVIDEND_YIELD_GROWTH_DIRECT_PLAN @ 24.3950 INR
```
