### ISSUE TITLE
Unable to get configuration file working with Docker compose

### ISSUE THREAD

**Issue by ghsysbug** [ananthakumaran/paisa#348]
**Describe your Environment**
OS: Arch Linux 6.14.6-arch1-1
Paisa Version: latest (0.7.3)
App Variant: Docker

**Describe the bug**
I am attempting to run a Docker compose file with a predefined `paisa.yaml` configuration file in the directory but each time I restart the server, or Docker image, paisa asks me to fill out a configuration file.

**To Reproduce**
1. `# docker compose up -d`
2. Open paisa at `paisa.example.com`
3. Paisa requires configuration settings

Alternatively:
1. Include `.env` file in compose file (see below)
2. Open paisa at `paisa.example.com`
3. 502 error

**Expected behavior**
Irrespective of how many times the server or the Docker image goes down, I would like paisa to retain the configuration saved in `paisa.yaml` so that in the event of any issue with either, paisa knows where to look for the configuration file based on the compose `.yml` or the location of the configuration file itself (which is in the same directory as the Docker files).

Just for completeness, I have also run `export PAISA_CONFIG=/home/user/paisa/paisa.yaml` on the server, but this does not seem to help.

**Docker compose files**
The following is the `docker-compose.yml` I am using;

```yaml
name: paisa
services:
    paisa:
        image: ananthakumaran/paisa:latest-hledger
        container_name: paisa
        restart: unless-stopped
        ports:
            - 127.0.0.1:7500:7500
        env_file:
            - .env
        volumes:
            - /home/user/paisa/:/home/user/paisa/
```

And the `.env` file;

```yaml
PAISA_CONFIG=paisa.yaml
```

**Comment by ghsysbug** [comment]
Somewhat solved; the initial configuration I was using was incorrect as I am a bit unfamiliar with Docker but trying to learn. 

In either case, I have removed the `.env` file as `paisa.yaml` is present in the volume I use and, as per the documentation on configuration (available [here](https://paisa.fyi/reference/config/)), this should be read before the document in the Docker volume itself (accessed via Portainer's console for the container).

The `docker-compose.yml` file now looks like this;

```yaml
name: paisa
services:
    paisa:
        image: ananthakumaran/paisa:latest-hledger
        container_name: paisa
        restart: unless-stopped
        ports:
            - 7500:7500
        volumes:
            - .:/root/Documents/paisa/
```

Additionally, the `paisa.yaml` file was changed. I think the only pertinent thing to note here is that I used the following values;

```yaml
journal_path: my.journal
db_path: my.db
```

Before this broadly successful run, I used absolute paths (and probably still could, but I did not test this), then I used `../my.journal` and `my.db`, which is erroneous.

Running `# docker compose up -d` with the above changes (ensuring `my.journal` shared the directory with the Docker compose file and Paisa configuration file).

Nonetheless, when I loaded into Paisa, I was greeted with the 'Looks like you're new here' screen. When I looked at the configuration values, however, they were correct. And double checking with the Docker console, I could see the values within the Docker container mirrored my server's folder for the configuration file.

I tried looking at the Assets tab, for instance, and it showed no transactions. The workaround involved going back to the Configuration tab and changing precision (as an example) from 2 to 1, then saving the changes, after which all transactions displayed properly. Nonetheless, it would be preferable that, when using one's own `paisa.yaml`, it is loaded without needing to do this.
