### ISSUE TITLE
Mutual Fund data is not getting updated.

### ISSUE THREAD

**Issue by avinashkanaujiya** [ananthakumaran/paisa#53]
In terminal, it is showing that Mutual Fund data is being pulled from Purified Bytes, which is for NPS schemes, after clicking Update Mutual Fund prices.

**Comment by ananthakumaran** [comment]
Mutual fund portfolios are fetched from https://purifiedbytes.com, it powers the analysis page https://demo.paisa.fyi/assets/analysis

**Comment by avinashkanaujiya** [comment]
Ok, so any idea why prices for Mutual Funds are not updating, I have added them to commodities page.

**Comment by ananthakumaran** [comment]
Can you share your commodity config here? I am assuming it might be related to the other issue as well.

**Comment by avinashkanaujiya** [comment]
Here it is,
```yaml
journal_path: /home/oops/Documents/paisa/main.ledger
db_path: /home/oops/Documents/paisa/paisa.db
ledger_cli: ledger
default_currency: INR
locale: en-IN
financial_year_starting_month: 4
retirement:
    swr: 3
    expenses:
        - Expenses:Rent
        - Expenses:Utilities
        - Expenses:Shopping
        - Expenses:Restaurants
        - Expenses:Food
        - Expenses:Interest:*
    savings:
        - Assets:Debt:*
        - Assets:Equity:*
    yearly_expenses: 0
schedule_al:
    - code: bank
      accounts:
        - Assets:Checking
    - code: share
      accounts:
        - Assets:Equity:*
        - Assets:Debt:*
    - code: liability
      accounts:
        - Liabilities:Homeloan
allocation_targets:
    - name: Debt
      target: 10
      accounts:
        - Assets:Debt:*
    - name: Equity
      target: 90
      accounts:
        - Assets:Stocks:*
        - Assets:Equity:*
commodities:
    - name: PPFCF-DP
      type: mutualfund
      price:
        provider: in-mfapi
        code: "122639"
      harvest: 365
      tax_category: equity
    - name: TITSF-DP
      type: mutualfund
      price:
        provider: in-mfapi
        code: "132756"
      harvest: 365
      tax_category: equity
    - name: NNMIF-DP
      type: mutualfund
      price:
        provider: in-mfapi
        code: "149892"
      harvest: 365
      tax_category: equity
    - name: IPNSIF-DP
      type: mutualfund
      price:
        provider: in-mfapi
        code: "149283"
      harvest: 365
      tax_category: equity
    - name: PPTSF-DP
      type: mutualfund
      price:
        provider: in-mfapi
        code: "147481"
      harvest: 365
      tax_category: equity
    - name: TITAN
      type: stock
      price:
        provider: com-yahoo
        code: TITAN.NS
      harvest: 0
      tax_category: equity
    - name: BAJFINANCE
      type: stock
      price:
        provider: com-yahoo
        code: BAJFINANCE.NS
      harvest: 0
      tax_category: equity
    - name: PIDILITIND
      type: stock
      price:
        provider: com-yahoo
        code: PIDILITIND.NS
      harvest: 0
      tax_category: equity
    - name: ASIANPAINT
      type: stock
      price:
        provider: com-yahoo
        code: ASIANPAINT.NS
      harvest: 0
      tax_category: equity
    - name: BERGEPAINT
      type: stock
      price:
        provider: com-yahoo
        code: BERGEPAINT.NS
      harvest: 0
      tax_category: equity
    - name: KOTAKBANK
      type: stock
      price:
        provider: com-yahoo
        code: KOTAKBANK.NS
      harvest: 0
      tax_category: equity
    - name: HDFCBANK
      type: stock
      price:
        provider: com-yahoo
        code: HDFCBANK.NS
      harvest: 0
      tax_category: equity
    - name: DIAMINESQ
      type: stock
      price:
        provider: com-yahoo
        code: DIAMINESQ.BO
      harvest: 0
      tax_category: equity
    - name: JYOTIRES
      type: stock
      price:
        provider: com-yahoo
        code: JYOTIRES.BO
      harvest: 0
      tax_category: equity
    - name: WAAREERTL
      type: stock
      price:
        provider: com-yahoo
        code: WAAREERTL.BO
      harvest: 0
      tax_category: equity
    - name: OVOBELE
      type: stock
      price:
        provider: com-yahoo
        code: OVOBELE.BO
      harvest: 0
      tax_category: equity

```
