### ISSUE TITLE
White screen on Linux Fedora x11

### ISSUE THREAD

**Issue by airtonix** [ananthakumaran/paisa#85]
**Describe your Environment**

Paisa self build from commit https://github.com/ananthakumaran/paisa/commit/a4194928902a9a88636454b1fccccf29990682ff

```
System:
  Host: brass Kernel: 6.4.4-200.fc38.x86_64 arch: x86_64 bits: 64
    Desktop: GNOME v: 44.3 Distro: Fedora release 38 (Thirty Eight)
Graphics:
  Device-1: NVIDIA GA102 [GeForce RTX 3090 Ti] driver: nvidia v: 535.54.03
  Display: x11 server: X.Org v: 1.20.14 with: Xwayland v: 22.1.9 driver: X:
    loaded: modesetting,nouveau,nvidia unloaded: fbdev,vesa
    gpu: nvidia,nvidia-nvswitch resolution: 1: 3440x1440~60Hz
    2: 3440x1440~60Hz 3: N/A
  API: OpenGL v: 4.6.0 NVIDIA 535.54.03 renderer: NVIDIA GeForce RTX 3090
    Ti/PCIe/SSE2
```

**Describe the bug**

making a build of the desktop app results in it launching with a white screen, however if you move your mouse around it's clearly reacting to clickables in the UI. 

This is a bug I've experienced with Wails before, easily fixed with this option: 

```go
			WebviewGpuPolicy:    linux.WebviewGpuPolicyNever,
```

**To Reproduce**

**Expected behavior**

Builds created for linux x11 should render the UI

**Screenshots**

**Journal**
If applicable, provide a minimal journal to help explain your problem.
